### ISSUE TITLE
Raid Tracking Features

### ISSUE THREAD

**Issue by QuitarHero** [QuitarHero/Heros-Marker-Pack#40]
I will be combining other issues into this one to consolidate all my goals with this.

- [ ]  **Boss Checklist:** Pictures that update with an `X` or a `✓` based on each individual user's weekly boss completion (requires an API key).
- [x] **Titles:** Each raid wing should have an identifying title above it. Since W7, the order that raid wings go in has been messed with, so this should add clarification. I am waiting for a `title` equivalent of `rotate` and `fadeNear/Far` to get this feature where I want it to be.
- [ ] **Chest Tracker:** Based on marker activation using a `behavior` that allows markers to reset on a weekly reset basis (which is currently not implemented), I can add a Chest marker by the wing's entrance that shows the user at a glance how many chests they acquired in a wing, via a `4/4` or `0/3`, etc (cross-marker interactivity is currently not implemented).

**Comment by QuitarHero** [comment]
will be implemented on monday thank you 2.5 year old me
