### ISSUE TITLE
TacO HpGrids

### ISSUE THREAD

**Issue by QuitarHero** [QuitarHero/Heros-Marker-Pack#41]
I've been working on HpGrids in my spare time, and this is a checklist of what I have done before I commit it to the pack.

**Fractals:**
- [x] Aquatic Ruins
- [x] Captain Mai Trin
- [x] Chaos Isles: Anomaly
- [x] Chaos Isles: Gladiator
- [x] Cliffside
- [x] Deepstone: Spider
- [x] Deepstone: Spark
- [x] Deepstone: Final Boss
- [x] Molten Boss: Effigy
- [x] Molten Boss: Boss Duo
- [x] Nightmare: MAMA
- [x] Nightmare: Siax
- [x] Nightmare: Ensolyss
- [x] Shattered Observatory: Skorvald
- [x] Shattered Observatory: Artsaiiv
- [x] Shattered Observatory: Arkk
- [x] Siren's Reef: Stoneback
- [x] Siren's Reef: Ship Bosses
- [x] Swampland: Mossman
- [x] Swampland: Bloomhunger
- [x] Thaumanova Reactor: Subject 6
- [x] Thaumanova Reactor: Anomaly
- [x] Twilight Oasis: Sandblinder `#0`
- [x] Twilight Oasis: Sandblinder `#1`
- [x] Twilight Oasis: Sandblinder `#2`
- [x] Twilight Oasis: Priestess Amala v1
- [x] Twilight Oasis: Priestess Amala v2
- [x] Volcanic: Grawl Shaman
- [x] Volcanic: Legendary Imbued Shaman

**Raids:**
- [x] Spirit Vale: Vale Guardian
- [x] Spirit Vale: Gorseval
- [x] Spirit Vale: Sabetha
- [x] Salvation Pass: Slothasor
- [x] Salvation Pass: Matthias
- [x] Stronghold: Keep Construct
- [x] Stronghold: Xera
- [x] Bastion: Cairn
- [x] Bastion: Mursaat Overseer
- [x] Bastion: Samarog
- [x] Bastion: Deimos
- [x] Hall of Chains: Soulless Horror
- [x] Hall of Chains: Dhuum
- [x] Mythwright Gambit: Twin Largos
- [x] Mythwright Gambit: Qadim
- [x] Ahdashim: Cardinal Sabir
- [x] Ahdashim: Cardinal Adina
- [x] Ahdashim: Qadim the Peerless

**Comment by QuitarHero** [comment]
Done.
